# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 01:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincontent', ckeditor.fields.RichTextField(verbose_name='正文')),
            ],
        ),
    ]
