# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 02:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_content_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pushcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('people', models.CharField(max_length=100)),
                ('maincontent', ckeditor.fields.RichTextField(verbose_name='正文')),
            ],
        ),
    ]
