# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 02:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_pushcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='maincontent',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
