# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='', verbose_name='pic_folder/'),
        ),
    ]
